server:
  port: 8082
spring:
  application:
    name: w2-demo-consumer
  config:
    import: optional:nacos:${spring.cloud.nacos.config.name},optional:nacos:${spring.application.name}
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:18848
        name: demo.yaml
        group: DEFAULT_GROUP
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:18848